apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: wyoming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: docker.io/rhasspy/wyoming-piper:latest
          resources:
            requests:
              memory: 1Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 4000m
          args:
            - --voice
            - en_US-lessac-medium
          ports:
            - containerPort: 10200
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: wyoming
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.3.11
    metallb.universe.tf/allow-shared-ip: piper
spec:
  selector:
    app: piper
  type: LoadBalancer
  ports:
    - name: piper
      protocol: TCP
      port: 10200
      targetPort: 10200
