apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure
  prune: true
  dependsOn:
    - name: sources
  sourceRef:
    kind: GitRepository
    name: flux-system
