apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
  name: bitwarden-secret
  namespace: knotdns
spec:
  organizationId: 077df9f9-efa8-41c5-bb5d-af96016781f5
  secretName: knotdns-init-storage-secret
  map:
    - bwSecretId: 9ee6640a-ce08-4bfa-97e8-b214016b6c77
      secretKeyName: j5t.io.zone
    - bwSecretId: b3776198-f8d7-42d1-b719-b214016ba34b
      secretKeyName: jarrett.net.zone
    - bwSecretId: 4013d44a-ca94-4041-b3fc-b2140172afb4
      secretKeyName: knot.conf
  authToken:
    secretName: bw-auth-token
    secretKey: token
  onlyMappedSecrets: true