apiVersion: v1
kind: Service
metadata:
  name: frigate-webrtc
  namespace: frigate
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.3.14
    metallb.universe.tf/allow-shared-ip: frigate
spec:
  selector:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  type: LoadBalancer
  ports:
    - name: webrtc
      port: 8555
      protocol: UDP
      targetPort: 8555
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: 8555
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-webrtc-tcp
  namespace: frigate
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.3.14
    metallb.universe.tf/allow-shared-ip: frigate
spec:
  selector:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  type: LoadBalancer
  ports:
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: 8555