apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu-helmrelease
  namespace: kube-system
spec:
  dependsOn:
    - name: intel-device-plugin-operator-helmrelease
  releaseName: intel-device-plugin-gpu
  interval: 2h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.34.1
      sourceRef:
        kind: HelmRepository
        name: intel-helmrepo
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    sharedDevNum: 2
    nodeFeatureRule: true
    denyIDs: "9bc5"  # Exclude UHD 630 iGPU, only expose discrete GPUs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-operator-helmrelease
  namespace: kube-system
spec:
  releaseName: intel-device-plugin-operator
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.34.1
      sourceRef:
        kind: HelmRepository
        name: intel-helmrepo
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
