apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
  name: bitwarden-secret
  namespace: frigate
spec:
  organizationId: 077df9f9-efa8-41c5-bb5d-af96016781f5
  secretName: frigate-secret
  map:
    - bwSecretId: a33f1600-a04f-4732-9947-b211002bfcf5
      secretKeyName: FRIGATE_MQTT_PASSWORD
    - bwSecretId: 73015edb-ebf6-426a-aebf-b211002c2795
      secretKeyName: FRIGATE_CAMERA_PASSWORD
    - bwSecretId: 739c80ea-8f83-49b3-bb9f-b211002c67bb
      secretKeyName: FRIGATE_CAMERA_4K
    - bwSecretId: 02fadd10-a5d9-489c-9ff9-b211002c82d3
      secretKeyName: FRIGATE_CAMERA_DRIVEWAY
    - bwSecretId: 2075a0f4-c3a5-4e74-8973-b2c7015f346c
      secretKeyName: PLUS_API_KEY
  authToken:
    secretName: bw-auth-token
    secretKey: token