apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate-helmrelease
  namespace: frigate
spec:
  releaseName: frigate
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: frigate-helmrepo
        namespace: flux-system
      version: 7.6.0
  interval: 5m
  install:
    createNamespace: true
  uninstall:
    disableHooks: true
  valuesFrom:
  - kind: ConfigMap
    name: frigate-helmchart-values-override
    valuesKey: values.yaml