apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
   email: evan@evanjarrett.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: letsencrypt-prod
   solvers:
     - dns01:
         cloudflare:
           apiTokenSecretRef:
             name: cloudflare-api-token-secret
             key: api-token
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-ai
spec:
  rules:
  - name: "google-coral-ai"
    labels:
      google-coral-ai: "true"
    matchFeatures:
    - feature: pci.device
      matchExpressions:
        device:
          op: In
          value:
          - 089a
        vendor:
          op: In
          value:
          - 1ac1
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rk3588
spec:
  rules:
  - name: "rk3588"
    labels:
      rk3588: "true"
    matchFeatures:
    - feature: cpu.model
      matchExpressions:
        family:
          op: In
          value:
          - "79"
        id:
          op: In
          value:
          - "53424"
