apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-openbao-services
  namespace: openbao
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gateway
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openbao-tls-route
  namespace: openbao
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - openbao.j5t.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: openbao
          namespace: openbao
          port: 8200
