apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jarrett-net
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    metallb.universe.tf/loadBalancerIPs: 192.168.3.135
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: homeassistant.jarrett.net
      name: homeassistantjarrettnet
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.jarrett.net"
      name: jarrettnet
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: jarrett-net-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: jarrett.net
      name: jarrettnetfull
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: jarrett-net-full-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: tny.click
      name: tnyclick
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: tnyclick-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: evanjarrett.com
      name: evanjarrettcom
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: evanjarrett-com-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: jarrett.tech
      name: jarretttech
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: jarrett-tech-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: j5t.io
      name: j5tiofull
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: j5t-io-full-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.j5t.io"
      name: j5tio
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: j5t-io-tls
        mode: Terminate
