apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jarrett-net
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    metallb.universe.tf/loadBalancerIPs: 192.168.3.1
spec:
  gatewayClassName: istio
  listeners:
    - name: jarrettnet
      hostname: "*.jarrett.net"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - website
              - proxy
              - loom-system
      tls:
        mode: Terminate
        certificateRefs:
          - name: jarrett-net-tls
    - name: jarrettnetfull
      hostname: "jarrett.net"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - website
      tls:
        mode: Terminate
        certificateRefs:
          - name: jarrett-net-full-tls
    - name: jarrettapp
      hostname: "*.jarrett.app"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - atproto
      tls:
        mode: Terminate
        certificateRefs:
          - name: jarrett-app-full-tls
    - name: jarrettappfull
      hostname: "jarrett.app"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - atproto
      tls:
        mode: Terminate
        certificateRefs:
          - name: jarrett-app-full-tls
    - name: tnyclick
      hostname: "tny.click"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - tnyclick
      tls:
        mode: Terminate
        certificateRefs:
          - name: tnyclick-tls
    - name: evanjarrettcom
      hostname: "evanjarrett.com"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
              - website
      tls:
        mode: Terminate
        certificateRefs:
          - name: evanjarrett-com-tls
    - name: j5tiofull
      hostname: "j5t.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: j5t-io-full-tls
    - name: j5tio
      hostname: "*.j5t.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: j5t-io-tls