apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-longhorn-services
  namespace: longhorn-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gateway
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: longhorn-tls-route
  namespace: longhorn-system
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - longhorn.j5t.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: Upgrade
                value: websocket
      backendRefs:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80
