---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: longhorn-tls-route
spec:
  parentRefs:
  - name: jarrett-net
    namespace: nginx-gateway
  hostnames:
  - "longhorn.jarrett.tech"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v1/
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
          - name: Upgrade
            value: websocket
    backendRefs:
    - name: longhorn-frontend
      namespace: longhorn-system
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: longhorn-frontend
      namespace: longhorn-system
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-header-services
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: nginx-gateway
  to:
  - group: ""
    kind: Service