apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: system-backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"  # Daily at 2 AM
  task: system-backup
  retain: 3
  concurrency: 3
  groups:
    - default
  parameters:
    volume-backup-policy: if-not-present
  labels:
    app: longhorn-backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  cron: "0 3 * * *"  # Daily at 3 AM (after backups)
  task: snapshot-cleanup
  retain: 10
  concurrency: 3
  groups:
    - default
  labels:
    app: longhorn-cleanup