apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu-operator-helmrelease
  namespace: kube-system
spec:
  releaseName: amd-gpu-operator
  interval: 2h
  chart:
    spec:
      chart: gpu-operator-charts
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-operator-helmrepo
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deviceConfig:
      selector:
        feature.node.kubernetes.io/custom-amd.gpu: "true"
