apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-helmrelease
  namespace: bitwarden
spec:
  releaseName: bitwarden-sm-operator
  chart:
    spec:
      chart: sm-operator
      sourceRef:
        kind: HelmRepository
        name: bitwarden-helmrepo
        namespace: flux-system
      version: 0.1.0-Beta
  interval: 2h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    containers:
      manager:
        image:
          repository: ghcr.io/evanjarrett/sm-operator
          tag: dev