apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitswarden-helmrelease
  namespace: flux-system
spec:
  releaseName: bitswarden-sm-operator
  chart:
    spec:
      chart: sm-operator
      sourceRef:
        kind: HelmRepository
        name: bitswarden-helmrepo
        namespace: flux-system
      version: 0.1.0-Beta
  interval: 2h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
