apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-helmrelease
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager-helmrepo
        namespace: flux-system
      version: v1.15.3
  interval: 5m0s
  install:
    createNamespace: true
  values:
    installCRDs: true