apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-helmrelease
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager-helmrepo
        namespace: flux-system
      version: v1.16.3
  interval: 2h
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
