apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs-helmrelease
  namespace: kube-system
spec:
  releaseName: csi-driver-nfs
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs-helmrepo
        namespace: flux-system
      version: v4.10.0
  interval: 2h
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true
