apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-helmrelease
  namespace: external-secrets
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets-helmrepo
        namespace: flux-system
      version: 0.19.1
  interval: 2h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace