apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate-helmrelease
  namespace: frigate
spec:
  releaseName: frigate
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: frigate-helmrepo
        namespace: flux-system
      version: 7.6.0
  interval: 2h
  install:
    createNamespace: true
  values:
    installCRDs: true
