apiVersion: v1
kind: Namespace
metadata:
  name: frigate
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: frigate-configmapgenerator
  namespace: frigate
configMapGenerator:
  - name: frigate-helmchart-values-override
    files:
      - values.yaml=frigate-values.conf
configurations:
  - frigate-kustomize.conf
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate-helmrelease
  namespace: frigate
spec:
  releaseName: frigate
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: frigate-helmrepo
        namespace: flux-system
      version: 7.6.0
  interval: 2h
  install:
    createNamespace: true
  values:
    installCRDs: true
  valuesFrom:
  - kind: ConfigMap
    name: frigate-helmchart-values-override
    valuesKey: values.yaml