apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate-helmrelease
  namespace: frigate
spec:
  releaseName: frigate
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: frigate-helmrepo
        namespace: flux-system
      version: 7.8.0
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  uninstall:
    disableHooks: true
  values:
    image:
      tag: 0.15.0
    envFromSecrets:
      - frigate-secret
    coral:
      enabled: true
      hostPath: /dev/apex_0
    extraVolumes:
      - name: coral-dev-two
        hostPath:
          path: /dev/apex_1
    extraVolumeMounts:
      - mountPath: /dev/apex_1
        name: coral-dev-two
    resources:
      requests:
        memory: "8Gi"
        cpu: "4"
        gpu.intel.com/i915: 1
      limits:
        memory: "16Gi"
        cpu: "4"
        gpu.intel.com/i915: 1
    securityContext:
      privileged: true
      capabilities:
        add: ["PERFMON"]
    nodeSelector:
      feature.node.kubernetes.io/coral.count: "2"
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
        skipuninstall: false
        ephemeralWritableConfigYaml: true
      media:
        enabled: true
        accessMode: ReadWriteOnce
        size: 100Gi
        skipuninstall: true
    config: |
      mqtt:
        enabled: true
        host: mqtt.proxy.svc.cluster.local
        port: 1883
        topic_prefix: frigate
        client_id: frigate
        user: mqtt
        password: "{FRIGATE_MQTT_PASSWORD}"
        stats_interval: 60
      ui:
        timezone: America/Chicago
      detectors:
        coral1:
          type: edgetpu
          device: pci:0
        coral2:
          type: edgetpu
          device: pci:1
      semantic_search:
        enabled: true
        model_size: large
        reindex: false
      genai:
        enabled: true
        provider: ollama
        base_url: http://ollama.ollama.svc.cluster.local:11434
        model: llava:7b
        prompt: "First, provide a brief visual description of the {label} captured by this residential security camera (size, color, shape, and notable features). Then analyze its presence in this neighborhood context - whether it appears to belong in this setting, how it came to be there, and any potential security implications. Consider its positioning relative to the property, any movement or changes over time, interactions with people/animals/vehicles, and whether its presence appears routine, expected, or unusual for a residential area. Note any behaviors or characteristics that might be relevant from a home security perspective."
        object_prompts:
          person: "First, provide a brief description of the person captured by this residential security camera (clothing colors/type, approximate age range, distinguishing features visible). Then: If on public areas (sidewalk/street): Note normal activities like walking or jogging. If on private property (driveway/yard/porch): Determine if they appear to be a resident, visitor, delivery person, gardener, or unkown. Only flag behaviors as concerning if showing specific suspicious actions (lingering at entry points, attempting access, unusual property interactions) rather than normal passage."
          car: "First, provide a brief description of the {label} captured by this residential security camera (color, make/model if identifiable, size/type). Then analyze its relationship to the residence - whether it appears to belong to the household, visitors, delivery services, or is unfamiliar to the area. Note parking duration, positioning relative to driveways/curbs, occupant activities, and any unusual patterns that might be relevant from a neighborhood security perspective."
          cat: "First, provide a brief description of the {label} captured by this residential security camera (size, color/markings, breed if identifiable). Then determine if it appears to be a household pet, a neighbor's pet, or wildlife. Focus on whether its presence is routine or unusual for this setting, any interaction with property, and any behaviors that might be concerning for residents (aggression, property damage, etc.)."
          dog: "First, provide a brief description of the {label} captured by this residential security camera (size, color/markings, breed if identifiable). Then determine if it appears to be a household pet, a neighbor's pet, or wildlife. Focus on whether its presence is routine or unusual for this setting, any interaction with property, and any behaviors that might be concerning for residents (aggression, property damage, etc.)."
      objects:
        track:
          - person
          - cat
          - car
          - dog
        filters:
          car:
            threshold: 0.7
      go2rtc:
        streams:
          4kcamera:
            - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_CAMERA_4K}:554/h264Preview_01_sub
            - "ffmpeg:4kcamera#video=h264#audio=aac"
          driveway:
            - rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@{FRIGATE_CAMERA_DRIVEWAY}:554/h264Preview_01_main
            - "ffmpeg:driveway#video=h264#audio=aac"
      record:
        enabled: true
        retain:
          days: 0
          mode: all
      ffmpeg:
        hwaccel_args: preset-intel-qsv-h264
        output_args:
          record: preset-record-generic-audio-copy
      cameras:
        4kcamera:
          ffmpeg:
            inputs:
            - path: rtsp://127.0.0.1:8554/4kcamera
              roles:
                - detect
                - record
          detect:
            enabled: true
          snapshots:
            enabled: true
            required_zones:
              - driveway-and-street
          zones:
            driveway-and-street:
              coordinates: 896,0,896,512,0,512,0,174,480,24,490,0
          objects:
            filters:
              car:
                mask: 0.143,0.071,0.333,0.016,0.274,0,0.139,0
          review:
            alerts:
              required_zones: driveway-and-street
        driveway:
          ffmpeg:
            inputs:
            - path: rtsp://127.0.0.1:8554/driveway
              roles:
                - detect
                - record
          detect:
            enabled: true
          snapshots:
            enabled: true
            required_zones:
              - front_house
          zones:
            front_house:
              coordinates: 0,1920,2560,1920,2560,1302,2560,751,2505,739,2347,708,2220,622,2211,346,1697,304,1155,297,525,358
          objects:
            filters:
              person:
                min_area: 1000
                mask: 1350,500,1300,500,1300,400,1350,400
              car:
                min_area: 10000