apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-helmrelease
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-helmrepo
        namespace: flux-system
      version: 8.14.2
  interval: 2h
  timeout: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    persistence:
      type: pvc
      enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: victoriametrics
            type: prometheus
            orgId: 1
            url: http://victoria-metrics-cluster-vmselect.monitoring.svc.cluster.local:8481/select/0/prometheus/
            access: proxy
            isDefault: true
            updateIntervalSeconds: 10
            editable: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        victoriametrics:
          gnetId: 11176
          revision: 18
          datasource: victoriametrics
        vmagent:
          gnetId: 12683
          revision: 7
          datasource: victoriametrics
        kubernetes:
          gnetId: 14205
          revision: 1
          datasource: victoriametrics