apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-helmrelease
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio-helmrepo
        namespace: flux-system
      version: 1.24.0-alpha.0
  interval: 2h
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod-helmrelease
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-helmrepo
        namespace: flux-system
      version: 1.24.0-alpha.0
  interval: 2h
  dependsOn:
    - name: istio-helmrelease
      namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway-helmrelease
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio-helmrepo
        namespace: flux-system
      version: 1.24.0-alpha.0
  interval: 2h
  dependsOn:
    - name: istiod-helmrelease
      namespace: istio-system
  install:
    createNamespace: true
    remediation:
      retries: 10
  values:
    installCRDs: true
    kind: Daemonset
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.3.135
