apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-helmrelease
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-helmrepo
        namespace: flux-system
      version: 1.10.1
  interval: 2h
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      storageReservedPercentageForDefaultDisk: 0
      storageMinimalAvailablePercentage: 10
      guaranteedInstanceManagerCPU: 12
    defaultBackupStore:
      backupTarget: "nfs://192.168.1.100:/mnt/Pool-1.18.6/longhorn"
    persistence:
      defaultClass: true

