apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin-helmrelease
  namespace: kube-system
spec:
  releaseName: nvidia-device-plugin
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.4
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin-helmrepo
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runtimeClassName: nvidia
    gfd:
      enabled: true
    nfd:
      enabled: false
    config:
      name: nvd-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvd-config
  namespace: kube-system
data:
  any: |-
    version: v1
    flags:
      migStrategy: none
      nvidiaDriverRoot: /
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 2