apiVersion: v1
kind: Namespace
metadata:
  name: ollama
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-helmrelease
  namespace: ollama
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama-helmrepo
        namespace: flux-system
      version: 1.23.0
  interval: 2h
  timeout: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    runtimeClassName: nvidia
    extraEnv:
      - name: OLLAMA_CONTEXT_LENGTH
        value: "16384"
    ollama:
      gpu:
        enabled: true
        type: nvidia
        number: 1
      models:
        pull:
          - PetrosStav/gemma3-tools:4b
          - nomic-embed-text
        run:
          - PetrosStav/gemma3-tools:4b
