apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-helmrelease
  namespace: ollama
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama-helmrepo
        namespace: flux-system
      version: 1.4.0
  interval: 2h
  timeout: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    runtimeClassName: nvidia
    gpu:
      enabled: true
      type: nvidia
      number: 1
    models:
      pull:
        - llama3.1:8b