---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui-helmrelease
  namespace: ollama
spec:
  releaseName: open-webui
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui-helmrepo
        namespace: flux-system
      version: 6.16.0
  interval: 2h
  timeout: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    pipelines:
        enabled: false
    ollama:
        enabled: false
    ollamaUrls: 
        - http://ollama:11434
    persistence:
      provider: s3
      s3:
        endpointUrl: https://gateway.storjshare.io
        bucket: openwebui
        accessKey: jw6yimpc7dxhu2mycfbdy6eboexa
        secretKeyExistingSecret: stroj
        secretKeyExistingSecretKey: secret