apiVersion: v1
kind: Namespace
metadata:
  name: openbao
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao-helmrelease
  namespace: openbao
spec:
  releaseName: openbao
  chart:
    spec:
      chart: openbao
      sourceRef:
        kind: HelmRepository
        name: openbao-helmrepo
        namespace: flux-system
      version: 0.16.2
  interval: 2h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    agentImage:
      repository: "openbao/openbao-hsm-ubi"
      tag: "2.3.2"