---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui-helmrelease
  namespace: ollama
spec:
  releaseName: open-webui
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui-helmrepo
        namespace: flux-system
      version: 8.0.0
  interval: 2h
  timeout: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    persistence:
      enabled: true
      existingClaim: open-webui-storage-claim
    pipelines:
        enabled: false
    ollama:
        enabled: false
    postgresql:
        enabled: true
    ollamaUrls: 
        - http://ollama:11434
    commonEnvVars:
      - name: DEFAULT_MODELS
        value: PetrosStav/gemma3-tools:4b
      - name: PDF_EXTRACT_IMAGES
        value: "true"
      - name: RAG_OLLAMA_BASE_URL
        value: http://ollama:11434
      - name: RAG_EMBEDDING_ENGINE
        value: ollama
      - name: RAG_EMBEDDING_MODEL
        value: nomic-embed-text
      - name: ENABLE_WEB_SEARCH
        value: "true"
      - name: WEB_SEARCH_ENGINE
        value: duckduckgo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-storage-claim
  namespace: ollama
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi