apiVersion: v1
kind: Namespace
metadata:
  name: openbao
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao-helmrelease
  namespace: openbao
spec:
  releaseName: openbao
  chart:
    spec:
      chart: openbao
      sourceRef:
        kind: HelmRepository
        name: openbao-helmrepo
        namespace: flux-system
      version: 0.16.2
  interval: 2h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    server:
      nodeSelector:
        feature.node.kubernetes.io/pico-hsm: "true"
      standalone:
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            # Enable unauthenticated metrics access (necessary for Prometheus Operator)
            #telemetry {
            #  unauthenticated_metrics_access = "true"
            #}
          }
          storage "file" {
            path = "/openbao/data"
          }

          # seal "pkcs11" {
          #   lib = "/usr/local/lib/libsofthsm2.so"
          #   slot = "0"
          #   token_label = "Pico-HSM"
          #   key_label = "bao-root-key-rsa"
          #   rsa_oaep_hash = "sha1"
          #   mechanism = "CKM_RSA_PKCS_OAEP"
          # }

          # Example configuration for enabling Prometheus metrics in your config.
          #telemetry {
          #  prometheus_retention_time = "30s"
          #  disable_hostname = true
          #}
      extraSecretEnvironmentVars:
        - envName: BAO_HSM_PIN
          secretName: hsm-secrets
          secretKey: pin
      resources:
        limits:
          squat.ai/pico-hsm: 1
      image:
        repository: "openbao/openbao-hsm-ubi"
        tag: "2.3.2"
      # Shared volume for PKCS#11 library
      volumes:
        - name: pkcs11-lib
          emptyDir: {}
      volumeMounts:
        - name: pkcs11-lib
          mountPath: /usr/local/lib
          readOnly: true
      securityContext:
        statefulSet:
          pod:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
      # Init container to install softhsm
      extraInitContainers:
        - name: pkcs11-installer
          image: ghcr.io/evanjarrett/alpine-softhsm:ubi
          command:
            - /bin/sh
            - -c
            - |
              cp /usr/lib64/libsofthsm2* /usr/local/lib
              cp /usr/lib64/libsqlite3* /usr/local/lib
              cp /usr/lib64/libgcc_s* /usr/local/lib
              cp /usr/lib64/libstdc++* /usr/local/lib
              cp /usr/lib64/libcrypto* /usr/local/lib
              cp /usr/bin/softhsm* /usr/local/lib/
              chmod +x /usr/local/lib/*
              ls -la /usr/local/lib/
          volumeMounts:
            - name: pkcs11-lib
              mountPath: /usr/local/lib