apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-helmrelease
  namespace: kube-system
spec:
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-helmrepo
        namespace: flux-system
      version: 2.17.0
  interval: 2h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
