apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-helmrelease
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-helmrepo
        namespace: flux-system
      version: 2.16.1
  interval: 5m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace