apiVersion: v1
kind: Namespace
metadata:
  name: secret-service
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secret-service-helmrelease
  namespace: secret-service
spec:
  chart:
    spec:
      chart: secret-service-operator
      sourceRef:
        kind: HelmRepository
        name: secret-service-helmrepo
        namespace: flux-system
      version: 0.1.0
  interval: 2h
  install:
    createNamespace: true
    remediation:
      retries: 3
