apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/gateway-api.git
  ref:
    tag: v1.3.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api-repo
  timeout: 5m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: node-feature-discovery-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/kubernetes-sigs/node-feature-discovery.git
  ref:
    tag: v0.17.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./deployment/overlays/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: node-feature-discovery-repo
  timeout: 5m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
  ref:
    tag: v0.9.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/standalone
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver-repo
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helmcharts
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./helmcharts
  prune: true
  dependsOn:
    - name: gateway-api-crds
    - name: node-feature-discovery-crds
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./namespaces
  prune: true
  dependsOn:
    - name: helmcharts
  timeout: 5m0s
