apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-helmrepo
  namespace: flux-system
spec:
  url: https://charts.jetstack.io
  interval: 10m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb-helmrepo
  namespace: flux-system
spec:
  url: https://metallb.github.io/metallb
  interval: 10m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets-helmrepo
  namespace: flux-system
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 10m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio-helmrepo
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 10m0s