apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-helmrepo
  namespace: flux-system
spec:
  url: https://charts.jetstack.io
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb-helmrepo
  namespace: flux-system
spec:
  url: https://metallb.github.io/metallb
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-helmrepo
  namespace: flux-system
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio-helmrepo
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel-helmrepo
  namespace: flux-system
spec:
  url: https://intel.github.io/helm-charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: frigate-helmrepo
  namespace: flux-system
spec:
  url: https://blakeblackshear.github.io/blakeshome-charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs-helmrepo
  namespace: flux-system
spec:
  url: https://openebs.github.io/openebs
  interval: 2h
