apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-helmrepo
  namespace: flux-system
spec:
  url: https://charts.jetstack.io
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb-helmrepo
  namespace: flux-system
spec:
  url: https://metallb.github.io/metallb
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-helmrepo
  namespace: flux-system
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio-helmrepo
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel-helmrepo
  namespace: flux-system
spec:
  url: https://intel.github.io/helm-charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: frigate-helmrepo
  namespace: flux-system
spec:
  url: https://blakeblackshear.github.io/blakeshome-charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-helmrepo
  namespace: flux-system
spec:
  url: https://charts.longhorn.io
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitwarden-helmrepo
  namespace: flux-system
spec:
  url: https://charts.bitwarden.com
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-helmrepo
  namespace: flux-system
spec:
  url: https://grafana.github.io/helm-charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics-helmrepo
  namespace: flux-system
spec:
  url: https://victoriametrics.github.io/helm-charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server-helmrepo
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/metrics-server
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs-helmrepo
  namespace: flux-system
spec:
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia-helmrepo
  namespace: flux-system
spec:
  url: https://helm.ngc.nvidia.com/nvidia
  interval: 2h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secret-service-helmrepo
  namespace: flux-system
spec:
  url: https://evanjarrett.github.io/secret-service-operator
  interval: 1m
