---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral
spec:
  rules:
  - name: google-coral
    labelsTemplate: |
      {{ $index := 0 }}
      {{ range .pci.device }}coral-apex-{{ $index }}.present=true
      {{ $index = add $index 1 }}
      {{ end }}
    matchFeatures:
    - feature: pci.device
      matchExpressions:
        device:
          op: In
          value:
          - 089a
        vendor:
          op: In
          value:
          - 1ac1
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rk3588
spec:
  rules:
  - name: "rk3588"
    labels:
      rk3588: "true"
    matchFeatures:
    - feature: cpu.model
      matchExpressions:
        family:
          op: In
          value:
          - "79"
        id:
          op: In
          value:
          - "53424"
