---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral
spec:
  rules:
    - name: google-coral
      labels:
        coral.present: "true"
      labelsTemplate: |
        coral.count={{ .pci.device | len }}
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            device:
              op: In
              value:
                - 089a
            vendor:
              op: In
              value:
                - 1ac1
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rk3588
spec:
  rules:
    - name: "rk3588"
      labels:
        rk3588: "true"
      matchFeatures:
        - feature: cpu.model
          matchExpressions:
            family:
              op: In
              value:
                - "79"
            id:
              op: In
              value:
                - "53424"
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: pico-hsm-rule
spec:
  rules:
  - name: "pico-hsm"
    labels:
      "feature.node.kubernetes.io/pico-hsm": "true"
    matchFeatures:
    - feature: usb.device
      matchExpressions:
            device:
              op: In
              value:
                - '4230'
            vendor:
              op: In
              value:
                - 20a0
