apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
  name: bitwarden-secret
  namespace: proxy
spec:
  organizationId: 077df9f9-efa8-41c5-bb5d-af96016781f5
  secretName: endpoint-secret
  map:
  - bwSecretId: c768d5fc-dbfb-4dd6-968e-b215015a79d3
    secretKeyName: calendar
  - bwSecretId: 461fbe97-9d1e-4a05-9f3c-b215015aade3
    secretKeyName: contacts
  - bwSecretId: f73daf1c-55cc-4f6e-abed-b2150159f509
    secretKeyName: homeassistant
  - bwSecretId: 79b7395c-b48b-49af-8d66-b215015a122e
    secretKeyName: jellyfin
  - bwSecretId: 8191760b-a5a0-4fd2-8289-b2150159d058
    secretKeyName: omada
  - bwSecretId: f649830b-a44f-40a8-af4f-b215015a3486
    secretKeyName: opendtu
  - bwSecretId: 1b7cb1a3-1d79-418a-a389-b215015a8f8b
    secretKeyName: photos
  - bwSecretId: 1f78019d-d7ff-4b7a-9fb7-b215015a6004
    secretKeyName: synology
  authToken:
    secretName: bw-auth-token
    secretKey: token