apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-tls-route
  namespace: proxy
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - jellyfin.jarrett.tech
  rules:
    - backendRefs:
        - name: jellyfin
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: proxy
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8096
  type: ClusterIP
