apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: omada-tls-route
spec:
  parentRefs:
  - name: jarrett-net
    namespace: gateway
  hostnames:
  - omada.jarrett.tech
  rules:
  - backendRefs:
    - name: omada
      namespace: proxy
      port: 80
---
apiVersion: v1
kind: Service
metadata:
 name: omada
spec:
  ports:
   - name: web
     port: 80
     targetPort: 80
  type: ClusterIP
---
