apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opendtu-tls-route
  namespace: proxy
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - opendtu.j5t.io
  rules:
    - backendRefs:
        - name: opendtu
          port: 80
