apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: synology-tls-route
  namespace: proxy
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - synology.jarrett.net
  rules:
    - backendRefs:
        - name: synology
          namespace: proxy
          port: 5000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: photos-tls-route
  namespace: proxy
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - photos.jarrett.net
  rules:
    - backendRefs:
        - name: photos
          namespace: proxy
          port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: calendar-tls-route
  namespace: proxy
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - calendar.jarrett.net
  rules:
    - backendRefs:
        - name: calendar
          namespace: proxy
          port: 8082
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: contacts-tls-route
  namespace: proxy
spec:
  parentRefs:
    - name: jarrett-net
      namespace: gateway
  hostnames:
    - contacts.jarrett.net
  rules:
    - backendRefs:
        - name: contacts
          namespace: proxy
          port: 8083
