apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
  name: bitwarden-secret
  namespace: ollama
spec:
  organizationId: 077df9f9-efa8-41c5-bb5d-af96016781f5
  secretName: open-webui-secret
  map:
    - bwSecretId: b52234f5-982e-4ade-b222-b2e70164f7a3
      secretKeyName: S3_ACCESS_KEY_ID
    - bwSecretId: 55ac9044-cf1f-40df-992e-b2e701651486
      secretKeyName: S3_SECRET_ACCESS_KEY
  authToken:
    secretName: bw-auth-token
    secretKey: token
  onlyMappedSecrets: true