apiVersion: v1
kind: Namespace
metadata:
  name: atproto
---
apiVersion: v1
kind: Service
metadata:
  name: atproto-pds
  namespace: atproto
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: atproto-pds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atproto-pds
  namespace: atproto
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: atproto-pds
  template:
    metadata:
      labels:
        app: atproto-pds
    spec:
      securityContext: {}
      containers:
        - name: atproto-pds
          securityContext: {}
          image: ghcr.io/bluesky-social/pds:0.4.158
          imagePullPolicy: IfNotPresent
          env:
            - name: PDS_HOSTNAME
              value: jarrett.app
            - name: PDS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bluesky
                  key: jwtSecret
            - name: PDS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bluesky
                  key: adminPassword
            - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: bluesky
                  key: plcRotationKey
            - name: PDS_EMAIL_SMTP_URL
              valueFrom:
                secretKeyRef:
                  name: bluesky
                  key: smtpServer
            - name: PDS_EMAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: bluesky
                  key: smtpFromAddress
            - name: PDS_DATA_DIRECTORY
              value: "/pds"
            - name: PDS_BLOBSTORE_DISK_LOCATION
              value: "/pds/blocks"
            - name: PDS_DID_PLC_URL
              value: "https://plc.directory"
            - name: PDS_BSKY_APP_VIEW_URL
              value: "https://api.bsky.app"
            - name: PDS_BSKY_APP_VIEW_DID
              value: "did:web:api.bsky.app"
            - name: PDS_REPORT_SERVICE_URL
              value: "https://mod.bsky.app"
            - name: PDS_REPORT_SERVICE_DID
              value: "did:plc:ar7c4by46qjdydhdevvrndac"
            - name: PDS_CRAWLERS
              value: "https://bsky.network"
            - name: LOG_ENABLED
              value: "true"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /pds
          livenessProbe:
            httpGet:
              path: /xrpc/_health
              port: http
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - name: pdsadmin-sidecar
          image: curlimages/curl:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              curl -o /shared/pdsadmin.sh https://raw.githubusercontent.com/bluesky-social/pds/refs/heads/main/pdsadmin.sh
              chmod +x /shared/pdsadmin.sh
              tail -f /dev/null
          volumeMounts:
            - name: shared-scripts
              mountPath: /shared
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pds-storage-claim
        - name: shared-scripts
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-storage-claim
  namespace: atproto
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi