apiVersion: v1
kind: Namespace
metadata:
  name: atproto
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atproto-pds-config
  namespace: atproto
data:
  PDS_HOSTNAME: "jarrett.app"
  PDS_DATA_DIRECTORY: "/pds"
  PDS_BLOBSTORE_DISK_LOCATION: "/pds/blocks"
  PDS_DID_PLC_URL: "https://plc.directory"
  PDS_BSKY_APP_VIEW_URL: "https://api.bsky.app"
  PDS_BSKY_APP_VIEW_DID: "did:web:api.bsky.app"
  PDS_REPORT_SERVICE_URL: "https://mod.bsky.app"
  PDS_REPORT_SERVICE_DID: "did:plc:ar7c4by46qjdydhdevvrndac"
  PDS_CRAWLERS: "https://bsky.network"
  LOG_ENABLED: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: atproto-pds
  namespace: atproto
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: atproto-pds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atproto-pds
  namespace: atproto
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: atproto-pds
  template:
    metadata:
      labels:
        app: atproto-pds
    spec:
      containers:
        - name: atproto-pds
          image: ghcr.io/bluesky-social/pds:0.4.158
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: atproto-pds-config
            - secretRef:
                name: bluesky
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /pds
          livenessProbe:
            httpGet:
              path: /xrpc/_health
              port: http
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - name: pdsadmin
          image: alpine:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              apk add --no-cache curl bash jq coreutils
              curl -o /usr/local/bin/pdsadmin https://raw.githubusercontent.com/bluesky-social/pds/refs/heads/main/pdsadmin.sh
              chmod +x /usr/local/bin/pdsadmin
              mkdir -p /pds
              touch /pds/pds.env
              tail -f /dev/null
          envFrom:
            - configMapRef:
                name: atproto-pds-config
            - secretRef:
                name: bluesky
          volumeMounts:
            - name: shared-scripts
              mountPath: /shared
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pds-storage-claim
        - name: shared-scripts
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-storage-claim
  namespace: atproto
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi