apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
  name: bitwarden-secret
  namespace: cert-manager
spec:
  organizationId: 077df9f9-efa8-41c5-bb5d-af96016781f5
  secretName: cloudflare-api-token-secret
  map:
    - bwSecretId: 0dc93e40-9155-4a7a-a809-b20f0165daa4
      secretKeyName: api-token
  authToken:
    secretName: bw-auth-token
    secretKey: token
    namespace: bitwarden
  onlyMappedSecrets: true