{
 "title": "Overview",
 "description": "Overview of the system",
 "tags": [ "version: main" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_metrics_prefix", "label": "Metrics Prefix" },
   { "name": "g_gpu_uuids", "query": { "query": "label_values(GPU_UUID)" } },
   { "name": "g_job_ids", "query": { "query": "label_values(job_id)" } },
   { "name": "g_cluster_name", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "GPUs",
   "type": "stat",
   "description": "Number of GPUs in the node",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}gpu_nodes_total{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "GPUs"
    },
    {
     "expr": "count(${g_metrics_prefix}gpu_health{cluster_name=\"$g_cluster_name\"} < 1)",
     "legendFormat": "Unhealthy GPUs"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "Number of jobs",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(job_id) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(job_id) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(group by(pod) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(group by(pod) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "description": "Total power usage, in Watts",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Current maximum PCIe speed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", ${g_metrics_prefix}pcie_max_speed{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_recovery_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Recovery"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_replay_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_replay_rollover_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_nack_received_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "sum(delta(${g_metrics_prefix}pcie_nack_sent_count{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Top 5 GPU Usage",
   "type": "stat",
   "description": "Top 5 current GPU GFX Activity, labeled with hostname, GPU ID, and job ID.",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by() (5, ${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}} | {{gpu_partition_id}} | {{job_id}}{{pod}}"
    },
    {
     "expr": "topk by() (5, ${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}} | {{gpu_partition_id}} | {{job_id}}{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs with highest VRAM used, labeled with hostname and GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, ${g_metrics_prefix}gpu_used_vram{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Current Total PCIe Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}pcie_bandwidth{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Total current PCIe bandwidth"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}gpu_used_vram{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(${g_metrics_prefix}gpu_total_vram{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "__auto"
    },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "\\# of GPUs allocated by jobs",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
     "legendFormat": "Busy GPUs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"} > 0))",
     "legendFormat": "Busy GPUs"
    }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "timeseries",
   "description": "Total PCIe Bandwidth over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}pcie_bandwidth{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Total PCIe Bandwidth"
    }
   ]
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Total accumulated energy consumed",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}gpu_energy_consumed{cluster_name=\"$g_cluster_name\"}[$__interval]))",
     "legendFormat": "Accumulated Energy Consumed (nJ)"
    },
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "GPU Usage"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"})",
     "legendFormat": "GPU Usage"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power, in Watts",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_package_power{cluster_name=\"$g_cluster_name\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "GPU Power"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_average_package_power{cluster_name=\"$g_cluster_name\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "GPU Power"
    }
   ]
  },
  {
   "title": "Average GPU Usage of Allocated GPUs",
   "type": "timeseries",
   "description": "Average of current allocated GPU GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or avg(${g_metrics_prefix}gpu_gfx_activity{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", job_id!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{cluster_name=\"$g_cluster_name\", pod!=\"\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\"}) or vector(0)",
     "legendFormat": "Allocated GPU Usage"
    }
   ]
  },
  {
   "title": "Average Memory Usage of Allocated GPUs",
   "type": "timeseries",
   "description": "Used VRAM of allocated GPUs over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Average current temperatures, in Celsius, from:\n- HBM (4 sensors)\n- Edge\n- Junction/hotspot",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_hbm_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "HBM Temperature"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "timeseries",
   "description": "Current temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_edge_temperature{cluster_name=\"$g_cluster_name\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_junction_temperature{cluster_name=\"$g_cluster_name\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(${g_metrics_prefix}gpu_memory_temperature{cluster_name=\"$g_cluster_name\"})",
     "legendFormat": "Memory Temperature"
    }
   ]
  },
  {
   "title": "All GPUs",
   "type": "table",
   "description": "List of all GPUs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_health{cluster_name=\"$g_cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "GPU",
 "description": "View by GPU",
 "tags": [ "version: main" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_metrics_prefix", "label": "Metrics Prefix" },
   {
    "name": "g_gpu_uuid",
    "label": "GPU UUID",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\", gpu_partition_id=\"$g_gpu_partition_id\"},gpu_uuid)"
    }
   },
   { "name": "g_cluster_name", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "g_hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\"},hostname)"
    }
   },
   {
    "name": "g_gpu_id",
    "label": "GPU ID",
    "query": {
     "query": "label_values({hostname=\"$g_hostname\"},gpu_id)"
    }
   },
   {
    "name": "g_gpu_partition_id",
    "label": "Partition",
    "query": {
     "query": "label_values({hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"},gpu_partition_id)"
    }
   },
   {
    "name": "g_gpu_vbios",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},vbios_version)"
    }
   },
   {
    "name": "g_driver",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},driver_version)"
    }
   },
   {
    "name": "g_card_vendor",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},card_vendor)"
    }
   },
   {
    "name": "g_card_series",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},card_series)"
    }
   },
   {
    "name": "g_card_model",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},card_model)"
    }
   },
   {
    "name": "g_serial_number",
    "query": {
     "query": "label_values({gpu_uuid=\"$g_gpu_uuid\"},serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "##### VENDOR\n${g_card_vendor}\n\n##### SERIES\n${g_card_series}\n\n##### MODEL\n${g_card_model}\n\n##### SERIAL\n${g_serial_number}\n\n##### UUID\n${g_gpu_uuid}"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": {
    "content": "#### HOST\n${g_hostname}\n\n#### GPU ID\n${g_gpu_id}\n\n#### PARTITION\n${g_gpu_partition_id}"
   }
  },
  {
   "title": "GPU Power Usage",
   "type": "gauge",
   "description": "GPU package power usage",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{\"${g_metrics_prefix}gpu_average_package_power\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    },
    {
     "expr": "{\"${g_metrics_prefix}gpu_package_power\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Current maximum PCIe speed",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}pcie_max_speed{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(${g_metrics_prefix}pcie_recovery_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}[$__interval])",
     "legendFormat": "Recovery"
    },
    {
     "expr": "delta(${g_metrics_prefix}pcie_replay_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}[$__interval])",
     "legendFormat": "Replay"
    },
    {
     "expr": "delta(${g_metrics_prefix}pcie_replay_rollover_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}[$__interval])",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "delta(${g_metrics_prefix}pcie_nack_received_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}[$__interval])",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "delta(${g_metrics_prefix}pcie_nack_sent_count{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}[$__interval])",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "description": "Most recent health status of GPU",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_health{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Bandwidth",
   "type": "timeseries",
   "description": "Current PCIe bandwidth over time",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}pcie_bandwidth{gpu_uuid=\"$g_gpu_uuid\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Usage",
   "type": "stat",
   "description": "% used VRAM of the GPU",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${g_metrics_prefix}gpu_used_vram{gpu_uuid=\"$g_gpu_uuid\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(${g_metrics_prefix}gpu_total_vram{gpu_uuid=\"$g_gpu_uuid\"})",
     "legendFormat": "__auto"
    },
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Total Correctable ECC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}gpu_ecc_correct_total{gpu_uuid=\"$g_gpu_uuid\"}[$__interval]))",
     "legendFormat": "Total Correctable ECC"
    }
   ]
  },
  {
   "title": "PCIe Bandwidth",
   "type": "stat",
   "description": "Current PCIe bandwidth",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}pcie_bandwidth{gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "{{hostname}}[{{gpu_id}}]"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": {
    "content": "#### VBIOS\n${g_gpu_vbios}\n\n#### DRIVER\n${g_driver}"
   }
  },
  {
   "title": "Energy Consumed",
   "type": "stat",
   "description": "Accumulated energy consumed",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 1000000", "type": "math" }
   ]
  },
  {
   "title": "Total Uncorrectable ECC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(${g_metrics_prefix}gpu_ecc_uncorrect_total{gpu_uuid=\"$g_gpu_uuid\"}[$__interval]))",
     "legendFormat": "Total Uncorrectable ECC"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "description": "Current GFX activity",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_gfx_activity{gpu_uuid=\"$g_gpu_uuid\", card_model=~\"102-D65208-0C|102-D67305-00|102-D65209-0C\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "GPU Usage"
    },
    {
     "expr": "avg(${g_metrics_prefix}gpu_gfx_busy_instantaneous{gpu_uuid=\"$g_gpu_uuid\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\", gpu_id=\"$g_gpu_id\"})",
     "legendFormat": "GPU Usage"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "Used VRAM on the GPU over time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "downsampler": "mean", "expression": "($A / $B) * 100", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "GPU Package Power",
   "type": "timeseries",
   "description": "GPU package power, in Watts",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_package_power{gpu_uuid=\"$g_gpu_uuid\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "${g_metrics_prefix}gpu_average_package_power{gpu_uuid=\"$g_gpu_uuid\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Current GPU temperature, in Celsius",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_edge_temperature{gpu_uuid=\"$g_gpu_uuid\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "${g_metrics_prefix}gpu_junction_temperature{gpu_uuid=\"$g_gpu_uuid\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C|102-G39205-00|102-G36220-0C|102-G36221-0C|102-G39206-00\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Current memory temperature, in Celsius",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_memory_temperature{gpu_uuid=\"$g_gpu_uuid\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "description": "Current temperatures, in Celsius:\n- 4 HBM temperatures\n- Edge temperature\n- Junction/hotspot temperature",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_hbm_temperature{gpu_uuid=\"$g_gpu_uuid\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "HBM - {{hbm_index}}"
    },
    {
     "expr": "${g_metrics_prefix}gpu_edge_temperature{gpu_uuid=\"$g_gpu_uuid\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "${g_metrics_prefix}gpu_junction_temperature{gpu_uuid=\"$g_gpu_uuid\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "GPU Errors",
   "type": "table",
   "description": "Error Name column values are the names of the metric queries themselves",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{__name__=~\".*ecc.*\", gpu_uuid=\"$g_gpu_uuid\", hostname=\"$g_hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Compute Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "${g_metrics_prefix}gpu_gfx_busy_instantaneous{gpu_uuid=\"$g_gpu_uuid\", card_model!~\"102-D65208-0C|102-D67305-00|102-D65209-0C\", gpu_id=\"$g_gpu_id\"}",
     "legendFormat": "CC - {{xcc_index}}"
    }
   ]
  }
 ]
}