apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: generic-device-plugin
  template:
    metadata:
      labels:
        name: generic-device-plugin
    spec:
      containers:
      - image: squat/generic-device-plugin
        name: generic-device-plugin
        args:
        - --device
        - |
          name: pico-hsm
          groups:
            - usb:
                - vendor: "20a0"
                  product: "4230"
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
