apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
  name: bitwarden-secret
  namespace: tnyclick
spec:
  organizationId: 077df9f9-efa8-41c5-bb5d-af96016781f5
  secretName: tnyclick-auth-token
  map:
  - bwSecretId: 51f871a8-701d-491e-be3e-b21601452c3b
    secretKeyName: AUTH_TOKEN
  authToken:
    secretName: bw-auth-token
    secretKey: token