---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCWpaFhnHcEw+3BApBZKsjzOAVfZ6/RrNrJwQiqDbd0U5Z/b0S6cH6X9SpFokxK6EwkZ8kips5SmTF1GGNeX9YiXIUK0mtzFgM8hkq2c02oZbuL0CbRSbmU1bdh8d4Dvgrzps7yxrGv3+bE9X5WmvO8F0g1bWYzN9tFXX/+wmMvhWPSKs2m1T3BfgP8rvHSh11sSziYfSpk3Oqbf9aMt76NmdS3NRlSK0SKQtjQZyZQigGP3jYFZ86Bl7V8jjnCtai76xlLygkZNujj6e2mxyCzq+w3ao6tI50G53TAi8mq7tbSUMsPOB8EcU349lTEHJ+RumuaQ2/jki+XEYaPTY4TcNM7IVDUY9uVIbgJLd3tjCr7GEl7f6TljV23ffZwrAiLk66/M3VrPhoYJnVzJnb6tIuCblKaRYEdtNb5NNatLOeuavtHyH8v7bvI2DwRjoozqXRfZXgsG/B8Af3luFWnQA5XAUEx+0HDIjJV1mMX94hvsy4+vCUu1sMilC8UXDgfgtQ9LiXUyBZsToz/Pt56qRzgxeqra24vh0KGopfFx/DdZ37ACZqUHvEQI628AniX0v3hUqbJ/axLT8MLXh8auy878nyP8vpQWfMMgD7VaoH+n2zN3aB6NA5YFqaR+RPozv5a2lcwooi9ukvLF+3HO3j1RvNPookuEE+RIZlGnXOPo4cQyWddJDRQZSytHngz3WfRA8prx8dRSsKXQRWKk4MUIcVKlSIQRshYEbk7s+B9+6u5zJCY
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
