---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: flux-system
spec:
  encryptedData:
    api-token: AgA/FUd7KpI3DjA9HzOl3DAG9vTSauwl2ekBjW0BlsZjYfW7PuGzhDnWXXraTcXjfg3c6urufipTXgEK3SM5cGx5Pd6gtIuKLmzZGhFheJq4/h2WOSPfDmijuzUM9lNban66LOHeKniOzALRbaU30ut5Q2SA917UBO+ghCY8p/8DjPDLHplH16OSpA9Uiol7ZfOHbMGS/O4AiTZoQ+psaFbuyV0Y1piOi4r3t+YRa6ohg+lIcCVnBs/AfB50pb61L7MCMdVfSJgBcOOGojbPDqi91N4U6Kw1OjIcnjrE9dmDSPycyjSUVBiP4NZClgULl/FBmf/OCezxcZEZeKlPtP6kGpr4/HUNj6FY/gwQzzuiSsCCfILpkGph7UuE75FhZs4FJm8iIQjPrXKrLwSZ6BdJbcWHRHlkRQsFDlc9PiXDuJWwM5RpY3Q7Wd+D5MShTZM87lxdZ91ArmN5cFWzMYQ+/wu4BMRk84jHJHpoFwWL29zbzrKg0uEzhy99MdZaLftgJv14MUKN6lwx3aXXRZkwu90rLrlP5ILmS5e7pXKv+rz1YuI9rrUgTSxiQhXfY6yaG9OjIb4n3yODt3+/qrfo/UQ0Y5sk6oGfiDJWfUU3ewF1POLxpioZxP66nptPWDI2B6mAla9hes1lgNcxVpPBFFaB/FYhixNBrhmBYSOViulSBv+G5GaYWZc2WbDo7+xassDxi6XReX+lqeZwkp4WWqga6RS7t2lbR/vOkklm0g+lsfC/rXER
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
