apiVersion: batch/v1
kind: Job
metadata:
  name: kubebench-manual-scan
  namespace: security
spec:
  template:
    spec:
      serviceAccountName: kubebench
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: kubebench
        image: aquasec/kube-bench:v0.8.0
        command: ["kube-bench"]
        args: 
          - --json
          - --benchmark
          - cis-1.23
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Never
      volumes: []
      nodeSelector:
        kubernetes.io/os: linux
  backoffLimit: 1