apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jellyfintwo-tls-route
  namespace: jellyfin
spec:
  parentRefs:
  - name: jarrett-net
    namespace: gateway
  hostnames:
  - "jellyfintwo.j5t.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: jellyfin-tcp
      port: 8096
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-udp
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - port: 7359
    targetPort: 7359
    name: discovery-udp
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.3.13
  sessionAffinity: ClientIP
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-tcp
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - port: 8096
    targetPort: 8096
    name: http-tcp
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.3.13
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-pvc
  namespace: jellyfin
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
        name: jellyfin
    spec:
      nodeSelector:
        #feature.node.kubernetes.io/rk3588: 'true'
        intel.feature.node.kubernetes.io/gpu: 'true'
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups:
          - 1000
      containers:
        - name: intel-gpu-top
          image: ubuntu:24.04 # Use Ubuntu 24.04 as the base image
          command: ["intel-gpu-top"]
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
              gpu.intel.com/i915: "1" # Request Intel GPU resource
          volumeMounts:
          - name: shared-bin
            mountPath: /usr/local/bin
        - name: "jellyfin"
          image: jellyfin/jellyfin
          ports:
          - containerPort: 8096
            name: http-tcp
            protocol: TCP
          - containerPort: 8920
            name: https-tcp
            protocol: TCP
          - containerPort: 1900
            name: dlna-udp
            protocol: UDP
          - containerPort: 7359
            name: discovery-udp
            protocol: UDP
          env:
          - name: JELLYFIN_PublishedServerUrl
            value: 192.168.3.13
          resources:
            limits:
              memory: "12Gi"
              cpu: "4"
              gpu.intel.com/i915: "1"
          volumeMounts:
          - name: jellyfin-cache
            mountPath: /cache
          - name: jellyfin-config
            mountPath: /config
          - name: jellyfin-transcode
            mountPath: /transcode
          - name: jellyfin-media
            mountPath: /media
      initContainers:
      - name: install-intel-gpu-tools
        image: ubuntu:24.04 # Use Ubuntu 24.04 for the init container
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y intel-gpu-tools && \
          cp /usr/bin/intel-gpu-top /shared-bin/
        volumeMounts:
        - name: shared-bin
          mountPath: /shared-bin
      volumes:
      - name: shared-bin
        emptyDir: {}
      - name: jellyfin-cache
        persistentVolumeClaim:
          claimName: jellyfin-cache-pvc
      - name: jellyfin-transcode
        emptyDir: {}
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: jellyfin-media
        nfs:
          server: 192.168.0.58
          path: /mnt/Pool-1.18.6/movies
